---
name: Terraform Infra plan - dev/feature1
on:
  push:
    branches:
      - dev/feature1
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: 'AKIAYCV63YPIBYCRLK7Q'
      aws_secret_access_key: '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'
      aws_region: 'us-east-1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: terraform plan
        if: github.event_name == 'push'
        run: terraform plan -input=false