name: "Terraform Infra plan - dev/feature1"

on:
  push:
    branches:
      - dev/feature1

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: ${{secrets.AWS_KEY_ID}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
      aws_region: "us-east-1"

steps:
  - name: Checkout Code
    uses: actions/checkout@v2

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v1
    with: terrafor_version: 0.15.0

  - name: Terraform Init
    id: init
    run: terraform init

  - name: terraform plan
    id: plan
    run: terraform plan -no-color