---
    name: Terraform InfraApply - main
    on:
      pull_request:
        types:
            - closed
        branches:
            - main
    jobs:
        if_merged:
            if: github.event.pull_request_merged == true
            runs-on: ubuntu-latest
            
            name: "Terraform"
            env:
                AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                AWS_REGION: 'us-east-1'
            steps:
            - name: Checkout Code
              uses: actions/checkout@v3
        
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
        
            - name: Terraform Init
              run: terraform init
        
            - name: terraform plan
              run: terraform plan -input=false

            - name: terraform apply
              run: terraform plan --auto-approve