---
name: Terraform Infra plan - dev/feature1
on:
  push:
    branches:
      - dev/feature1
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      aws_region: 'ap-south-1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: terraform plan
        if: github.event_name == 'push'
        run: terraform plan -input=false